# Generated by Django 5.0.6 on 2024-10-31 14:17

import employeeapp.validators
import location_field.models.plain
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True, validators=[employeeapp.validators.phonenumber_validation])),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('salon_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('can_view_survey', 'Can view survey'), ('can_edit_survey', 'Can edit survey'), ('can_delete_survey', 'Can delete survey'), ('can_send_survey', 'Can send survey'), ('can_create_survey', 'Can create survey'), ('can_create_question', 'Can create question'), ('can_view_question', 'Can view question'), ('can_edit_question', 'Can edit question'), ('can_delete_question', 'Can delete question'), ('can_create_customer', 'Can create customer'), ('can_view_customer', 'Can view customer'), ('can_edit_customer', 'Can edit customer'), ('can_delete_customer', 'Can delete customer'), ('can_respond_to_survey_response', 'Can respond to survey response'), ('can_view_survey_response', 'Can view survey response'), ('can_delete_survey_response', 'Can delete survey response')],
            },
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True, validators=[employeeapp.validators.phonenumber_validation])),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('can_view_survey', 'Can view survey'), ('can_edit_survey', 'Can edit survey'), ('can_send_survey', 'Can send survey'), ('can_create_survey', 'Can create survey'), ('can_create_question', 'Can create question'), ('can_view_question', 'Can view question'), ('can_edit_question', 'Can edit question'), ('can_delete_question', 'Can delete question'), ('can_create_customer', 'Can create customer'), ('can_view_customer', 'Can view customer'), ('can_edit_customer', 'Can edit customer'), ('can_respond_to_survey_response', 'Can respond to survey response'), ('can_view_survey_response', 'Can view survey response')],
            },
        ),
    ]
