# Generated by Django 5.0.6 on 2024-11-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salonowner',
            options={'permissions': [('can_view_survey', 'Can view survey'), ('can_edit_survey', 'Can edit survey'), ('can_delete_survey', 'Can delete survey'), ('can_send_survey', 'Can send survey'), ('can_create_survey', 'Can create survey'), ('can_create_question', 'Can create question'), ('can_view_question', 'Can view question'), ('can_edit_question', 'Can edit question'), ('can_delete_question', 'Can delete question'), ('can_create_customer', 'Can create customer'), ('can_view_customer', 'Can view customer'), ('can_edit_customer', 'Can edit customer'), ('can_delete_customer', 'Can delete customer'), ('can_create_stylist', 'Can create stylist'), ('can_view_stylist', 'Can view stylist'), ('can_edit_stylist', 'Can edit stylist'), ('can_delete_stylist', 'Can delete stylist'), ('can_respond_to_survey_response', 'Can respond to survey response'), ('can_view_survey_response', 'Can view survey response'), ('can_delete_survey_response', 'Can delete survey response')]},
        ),
        migrations.AlterModelOptions(
            name='stylist',
            options={'permissions': [('can_view_survey', 'Can view survey'), ('can_edit_survey', 'Can edit survey'), ('can_send_survey', 'Can send survey'), ('can_create_survey', 'Can create survey'), ('can_create_question', 'Can create question'), ('can_view_question', 'Can view question'), ('can_edit_question', 'Can edit question'), ('can_delete_question', 'Can delete question'), ('can_create_customer', 'Can create customer'), ('can_view_customer', 'Can view customer'), ('can_edit_customer', 'Can edit customer'), ('can_view_stylist', 'Can view stylist'), ('can_edit_stylist', 'Can edit stylist'), ('can_respond_to_survey_response', 'Can respond to survey response'), ('can_view_survey_response', 'Can view survey response')]},
        ),
    ]
