# Generated by Django 5.0.6 on 2024-10-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerapp', '0004_alter_customer_date_joined_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('CHOICE', 'Multiple Choice'), ('OPEN-ENDED', 'Open-Ended')], max_length=200)),
            ],
            options={
                'permissions': [('can_view_question', 'Can view question'), ('can_update_question', 'Can update question'), ('can_delete_question', 'Can delete question'), ('can_create_question', 'Can create question')],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('text', models.CharField(max_length=200)),
                ('question_type', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_view_survey', 'Can view survey'), ('can_edit_survey', 'Can edit survey'), ('can_delete_survey', 'Can delete survey'), ('can_send_survey', 'Can send survey'), ('can_respond_to_survey', 'Can respond to survey'), ('can_create_survey', 'Can create survey')],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.survey'),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('received_at', models.DateField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.survey')),
            ],
            options={
                'permissions': [('can_view_feedback', 'Can view feedback'), ('can_submit_feedback_to_salon', 'Can submit feedback to salon'), ('can_respond_to_feedback', 'Can respond to feedback'), ('can_delete_feedback', 'Can delete feedback')],
            },
        ),
    ]
