# Generated by Django 5.0.6 on 2024-10-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_alter_customer_date_joined_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_submit_survey_response', 'Can submit survey response')]},
        ),
    ]
